### ISSUE TITLE
[bug] remove ff -c ALL option 

### ISSUE THREAD

**Issue by rpappalax** [rpappalax/ff-tool#59]
python performs install then launch synchronously.  Launching browser leaves script in wait state so downloading next browser isn't possible til that activity is terminated.

We could perhaps spawn multiple threads??  @pdehaan

**Comment by pdehaan** [comment]
I'd assume that if you wanted to download ALL browsers, we should probably just set the [`--install-only` flag](https://github.com/rpappalax/ff-tool#download-all-browsers-but-dont-create-a-profile-or-launch-any-browsers) to `true`... Since I can't think of many cases where shotgunning 4 browsers open at the same time is probably what I wanted (since you'd need 4 different profiles, etc).

**Comment by rpappalax** [comment]
yea, i agree.  though right now the ALL option is lumped together like this:
  -c {release,beta,aurora,nightly,ALL}, --channel {release,beta,aurora,nightly,ALL}

the behavior for ff -c <channel> is to download, install, launch
ff -c ALL would just be download, install only
is that confusing?? (perhaps not...)
Anyway, I like your suggestion.  Let's go ahead and do that and let folks give feedback.

:dancer:

**Comment by pdehaan** [comment]
Agree? Yes. It is confusing. But I think the "ALL" hack was just a convenience for our nightly cleanup job, so we didn't need to call `ff -c [channel] --install-only` four times.

**Comment by rpappalax** [comment]
per our conversation, i'll  remove the ALL option

**Comment by rpappalax** [comment]
Done!
