### ISSUE TITLE
Add multi-browser instance launch capability

### ISSUE THREAD

**Issue by rpappalax** [rpappalax/ff-tool#91]
For testing interactive sessions (i.e. Hello Firefox, messaging, etc.), it can often be helpful to launch more than 1 browser.  This would be easy to implement, since we already start new browsers by default with a random profile name.
We could do something like:

~~~
-b --browser-count 3  
~~~

The tricky part would be if you wanted more than 1 release type, but this might be accomplished with an arg append.  Something like:

~~~
-c nightly -c release -c aurora
~~~

@pdehaan, @chartjes thoughts?

**Comment by pdehaan** [comment]
I'm not strongly attached to this concept.
This gets ugly _FAST_ because it'd be launching all 3 browsers with the same configs. Plus, there'd be no way of trying to launch a Nightly and Beta channel. You'd be stuck with X browsers with the same profile data (if that's even possible -- I know we cant launch with the same physical profile because it'd be in use for browsers 2 and 3).

Any huge benefit here versus just calling `$ ff --no-download` 3 times separately?

**Comment by rpappalax** [comment]
yea, i guess pretty limited.  i thought of testing Hello Firefox, but even then you wouldn't be able to do different channels without an arg combinatorial explosion. 
So, 👎  exterminate!
